import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import MapView, { Marker, PROVIDER_GOOGLE } from "react-native-maps";
import theme from "../../../../constants/theme";
import { listEvents } from "../../../../lib/customer-api";
import { normalizeMapEvent } from "../../../../lib/event-map-utils";
import type { CustomerMapEventPayload, CustomerMapEventsResponse, GeoCoordinates, NormalizedMapEvent } from "../../../../lib/event-map-types";
import { getCurrentCoords, isExpectedLocationError } from "../../../../lib/location";

type Props = { events?: NormalizedMapEvent[]; loading?: boolean };
export default function EventMap({ events: suppliedEvents, loading: suppliedLoading }: Props = {}) {
  const router = useRouter(); const [fetchedEvents, setFetchedEvents] = useState<NormalizedMapEvent[]>([]); const [location, setLocation] = useState<GeoCoordinates | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const events = suppliedEvents ?? fetchedEvents; const displayLoading = suppliedLoading ?? loading;
  const selected = events.find((event) => String(event.id) === selectedId) ?? null; const mappedEvents = useMemo(() => events.flatMap((event) => { const latitude = event.latitude ?? location?.latitude; const longitude = event.longitude ?? location?.longitude; return latitude != null && longitude != null ? [{ event, latitude, longitude }] : []; }), [events, location]);
  const load = useCallback(async () => { setLoading(true); try { const [payload, coords] = await Promise.all([listEvents<CustomerMapEventsResponse>({ limit: 100 }), getCurrentCoords()]); const items = Array.isArray(payload?.items) ? payload.items : []; setFetchedEvents(items.map((item: CustomerMapEventPayload) => normalizeMapEvent(item)).filter((event) => event.entityType === "event")); if (coords) setLocation({ latitude: coords.latitude, longitude: coords.longitude }); else setError("Turn on location access to see event locations."); } catch (value: unknown) { setError(value instanceof Error ? value.message : "Events could not be loaded."); if (!isExpectedLocationError(value)) console.error("Event map failed:", value); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (!location) return <View style={styles.state}>{displayLoading ? <><ActivityIndicator size="large" color={theme.COLORS.primary} /><Text style={styles.text}>Finding your current location…</Text></> : <><Ionicons name="location-outline" size={38} color={theme.COLORS.primary} /><Text style={styles.title}>Event map unavailable</Text><Text style={styles.text}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Try again</Text></TouchableOpacity></>}</View>;
  return <View style={styles.container}><MapView provider={PROVIDER_GOOGLE} style={StyleSheet.absoluteFillObject} initialRegion={{ latitude: location.latitude, longitude: location.longitude, latitudeDelta: 0.08, longitudeDelta: 0.08 }} showsUserLocation showsMyLocationButton={false}>{mappedEvents.map(({ event, latitude, longitude }) => <Marker key={String(event.id)} coordinate={{ latitude, longitude }} onPress={() => setSelectedId(String(event.id))}><View style={[styles.marker, selectedId === String(event.id) && styles.markerSelected]}><MaterialIcons name="event-note" size={selectedId === String(event.id) ? 25 : 22} color={theme.COLORS.primary} /></View></Marker>)}</MapView>{displayLoading ? <View style={styles.badge}><ActivityIndicator size="small" color={theme.COLORS.primary} /><Text>Updating events</Text></View> : !mappedEvents.length ? <View style={styles.badge}><Text>No events found.</Text></View> : null}{selected ? <View style={styles.preview}><Text style={styles.previewTitle}>{selected.title}</Text><Text style={styles.text}>{selected.location}</Text><TouchableOpacity style={styles.button} onPress={() => router.push(`/home/events/${selected.id}`)}><Text style={styles.buttonText}>View event</Text></TouchableOpacity></View> : null}</View>;
}
const styles = StyleSheet.create({ container: { flex: 1, minHeight: 560 }, state: { flex: 1, minHeight: 560, alignItems: "center", justifyContent: "center", padding: 24, gap: 8 }, title: { color: theme.COLORS.textPrimary, fontWeight: "700" }, text: { color: theme.COLORS.textSecondary, textAlign: "center" }, retry: { color: theme.COLORS.primary, fontWeight: "700", marginTop: 8 }, marker: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#fff", alignItems: "center", justifyContent: "center", elevation: 5 }, markerSelected: { borderWidth: 2, borderColor: theme.COLORS.primary }, badge: { position: "absolute", top: 16, alignSelf: "center", flexDirection: "row", gap: 8, padding: 10, borderRadius: 12, backgroundColor: "#fff" }, preview: { position: "absolute", left: 16, right: 16, bottom: 16, padding: 16, borderRadius: 16, backgroundColor: "#fff", elevation: 6 }, previewTitle: { color: theme.COLORS.textPrimary, fontSize: 16, fontWeight: "800" }, button: { marginTop: 10, padding: 10, borderRadius: 10, backgroundColor: theme.COLORS.primary, alignItems: "center" }, buttonText: { color: "#fff", fontWeight: "700" }, });
